### ISSUE TITLE
Broken path to AndroidManifest.xml with new Ionic version

### ISSUE THREAD

**Issue by oscarlocatelli** [gluelabs/pushape-cordova-push#1]
Ciao @m00s ,

sembra che con le nuove versioni di Ionic il path dell'AndroidManifest.xml sia cambiato da /app a /app/src/main.

Il file build.gradle all'interno di questo plugin amdrebbe aggiornato con il nuovo path.

Infatti copiando il file da /app/src/main/AndroidManifest.xml in /app/AndroidManifest.xml dopo il primo build fallito funziona tutto.

Ciao

**Comment by barbax** [comment]
Bug già risolto. Grazie @oscarlocatelli per la segnalazione
